# Your name and what you do
name: Shubham Singh
bio: Social Computing Researcher

description: Shubham Singh's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://shubhams.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: regexmachina
linkedin: shubhamsngh
github: shubhams
email: shubhamsingh19294@gmail.com
stackoverflow: 3832088/shubhamsingh
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    KidsGUARD:
        name: KidsGUARD
        description: A fine-grained deep learning framework to detect child unsage content on streaming platforms
        # url: https://github.com/jibolash/Eve
    InfoLeak:
        name: InfoLeak
        description: Detecting entity-specific leaks on the Internet and analyzing the damage caused
        # url: https://github.com/jibolash/world-cup-history
    Identity Resolution:
        name: Identity Resolution
        description: Identifying social profiles belonging to same user across social networks
        # url: https://tweetermum.herokuapp.com

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Python, Java, MATLAB, Javascript, C, C++
    - PyTorch, Keras, Numpy, Scikit, Flask, NodeJS, Celery, Android
    - MongoDB, MySQL, PostgreSQL
    - Git, Vim, Sublime, Jupyter, IntelliJ, LaTeX

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag
  - jemoji

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
